feat : Added the appointment API
Kavindu-248/DRF_Build pull request #11
Opened 2023-03-30 05:42 UTC by Kavindu-248

2023-03-30 06:34 UTC, Raam124 requested changes

2023-03-30 06:34 UTC, Raam124 commented on apps/assesment/views.py
> +    def perform_create(self, serializer):
add validation to check if the requested availability is already added to appointment or not

2023-03-30 06:34 UTC, Raam124 commented on apps/assesment/views.py
> +    def perform_create(self, serializer):
if added return a meaningful error message

2023-03-30 07:50 UTC, Kavindu-248 commented on apps/assesment/views.py
> +    def perform_create(self, serializer):
Noted .

2023-03-30 08:41 UTC, Raam124 requested changes

2023-03-30 08:41 UTC, Raam124 commented on apps/assesment/views.py
> +    def perform_create(self, serializer):
why is this still open ?

2023-03-31 05:38 UTC, Raam124 requested changes

2023-03-31 05:38 UTC, Raam124 commented on apps/assesment/views.py
need to appointment update API to update the status 
Also need the appointment to delete API to update the status to cancel

2023-03-31 07:25 UTC, closed without merging