feat: added the Appointment API
Kavindu-248/DRF_Build pull request #17
Opened 2023-03-31 07:34 UTC by Kavindu-248

2023-03-31 07:43 UTC, Kavindu-248 commented
This is a new PR previous one I mistakenly deleted a file trying to get the model changes, lesson learnt, I made the changes to update appointment to check statuses.

2023-03-31 08:19 UTC, Raam124 requested changes

2023-03-31 08:19 UTC, Raam124 commented on apps/assesment/views.py
> +        elif appointment.status == AppointmentStatus.CANCELED:
cancelled should be updated in DELETE request not in PUT

2023-03-31 09:22 UTC, Kavindu-248 commented on apps/assesment/views.py
> +        elif appointment.status == AppointmentStatus.CANCELED:
Overrode delete method for the given requirement

2023-03-31 09:38 UTC, Raam124 requested changes

2023-03-31 09:38 UTC, Raam124 commented on apps/assesment/views.py
> +        availability = Avalability.objects.get(id=appointment.availability.id)
if you have the appointment object you can directly get the related availability you don't have to query it again.

2023-03-31 09:38 UTC, Raam124 commented on apps/assesment/views.py
> +        availability = Avalability.objects.get(id=appointment.availability.id)
if you have the appointment object you can directly get the related availability you don't have to query it again.

2023-03-31 09:38 UTC, Raam124 commented on apps/assesment/views.py
> +        else:
the only possible thing to update here is COMPLETED status just manually check that with an if instead of passing the logic to else

2023-03-31 09:38 UTC, Raam124 commented on apps/assesment/views.py
> +        if appointment.status == AppointmentStatus.CANCELED:
you don't have to pass an error for an already cancelled appointment it will just override the value and it won't affect the functionality. here you should restrict the user from deleting and ongoing appointment with a readable error

2023-03-31 09:38 UTC, Raam124 commented on apps/assesment/views.py
> +    def perform_create(self, serializer):
you have to mark the appointment as booked when creating an appointment with that availability

2023-04-03 03:37 UTC, Kavindu-248 commented on apps/assesment/views.py
> +        availability = Avalability.objects.get(id=appointment.availability.id)
Noted.

2023-04-03 03:37 UTC, Kavindu-248 commented on apps/assesment/views.py
> +        else:
Changed the code to status COMPLETED and raised a valid error

2023-04-03 03:37 UTC, Kavindu-248 commented on apps/assesment/views.py
> +            availability.booked = False
Removed the code line

2023-04-03 03:44 UTC, Kavindu-248 commented on apps/assesment/views.py
> +        if appointment.status == AppointmentStatus.CANCELED:
Passed in the appointment status of ONGOING with an error of disallowing a user to DELETE an ongoing appointment

2023-04-03 04:08 UTC, Raam124 requested changes

2023-04-03 04:08 UTC, Raam124 commented on apps/assesment/views.py
> +        appointment.booked = True
does the appointment has a booked flag ?

2023-04-03 04:08 UTC, Raam124 commented on apps/assesment/views.py
> +        availability = Avalability.objects.get(id=appointment.availability.id)
why are you manually getting the availability again?

2023-04-03 04:08 UTC, Raam124 commented on apps/assesment/views.py
> +    def perform_update(self, serializer):
what if the appointment is in a canceled state?

2023-04-03 04:08 UTC, Raam124 commented on apps/assesment/views.py
> +    def perform_destroy(self, instance):
why are you deleting the instance here just update the status to cancelled

2023-04-04 08:39 UTC, Kavindu-248 commented on apps/assesment/views.py
> +    def perform_destroy(self, instance):
Status set to cancelled.

2023-04-04 08:39 UTC, Kavindu-248 commented on apps/assesment/views.py
> +    def perform_update(self, serializer):
Updated code with  cancelled status and raised  a validation error.

2023-04-04 08:39 UTC, Kavindu-248 commented on apps/assesment/views.py
> +        availability = Avalability.objects.get(id=appointment.availability.id)
I thought we have to pass the availabilty id in the payload of POST request, In the new commit I removed getting the appointment object

2023-04-04 09:34 UTC, Raam124 requested changes

2023-04-04 09:34 UTC, Raam124 commented on apps/assesment/views.py
> +            availability.booked = True
this only won't save the availability booked status

2023-04-04 09:34 UTC, Raam124 commented on apps/assesment/views.py
> +            appointment.status = AppointmentStatus.CANCELED
this only won't save the status to database

2023-04-04 09:34 UTC, Raam124 commented on apps/assesment/views.py
> +            super().perform_destroy(serializer)
did you checked if the appointment is only updated or entirely deleted ?

2023-04-06 03:57 UTC, Kavindu-248 commented on apps/assesment/views.py
> +            availability.booked = True
Amended code to save the availability

2023-04-06 03:57 UTC, Kavindu-248 commented on apps/assesment/views.py
> +            appointment.status = AppointmentStatus.CANCELED
Amended code to save the appointment

2023-04-06 03:57 UTC, Kavindu-248 commented on apps/assesment/views.py
> +            super().perform_destroy(serializer)
earlier I entirely deleted the appointment before , in the new commit I set the status to cancelled and saved the appointment

2023-04-06 04:02 UTC, Raam124 requested changes

2023-04-06 04:02 UTC, Raam124 commented on apps/assesment/views.py
> +            appointment.status = AppointmentStatus.CANCELED
@Kavindu-248 why this is not resolved?

2023-04-06 05:17 UTC, Kavindu-248 commented on apps/assesment/views.py
> +            appointment.status = AppointmentStatus.CANCELED
in the previous commit I did not access the serializer while saving, now its resolved.

2023-04-07 03:57 UTC, Raam124 approved these changes

2023-04-07 03:57 UTC, merged