feat: added the FormAssesment and Question APIs
Kavindu-248/DRF_Build pull request #18
Opened 2023-04-10 04:22 UTC by Kavindu-248

2023-04-10 04:32 UTC, Raam124 requested changes

2023-04-10 04:32 UTC, Raam124 commented on apps/assesment/views.py
> +class QuestionViewSet(viewsets.ViewSet):
this only have one GET API why are you using a viewset here ?

2023-04-10 04:32 UTC, Raam124 commented on apps/assesment/views.py
> +class FormAssesmentViewSet(viewsets.ModelViewSet):
check the features of form assessment feature once again

2023-04-12 04:16 UTC, Kavindu-248 commented on apps/assesment/views.py
> +class FormAssesmentViewSet(viewsets.ModelViewSet):
Rechecked and made changes

2023-04-18 04:07 UTC, Raam124 requested changes

2023-04-18 04:07 UTC, Raam124 commented on apps/assesment/views.py
> +    def perform_create(self, serializer):
what are the data that you getting here for form assessment post ?
how can you only get the answers without the questions ?

2023-04-25 04:58 UTC, Kavindu-248 commented on apps/assesment/views.py
> +    def perform_create(self, serializer):
resolved to get the questions by filtering with the treatment type.

2023-05-02 10:47 UTC, Raam124 approved these changes

2023-05-02 10:47 UTC, merged