feat: added the Medicine API
Kavindu-248/DRF_Build pull request #19
Opened 2023-05-03 03:08 UTC by Kavindu-248

2023-05-04 03:45 UTC, Raam124 requested changes

2023-05-04 03:45 UTC, Raam124 commented on apps/dispensary/views.py
> +class MedicineViewSet(viewsets.ModelViewSet):
we're don't need the entire CRUD for medicine. we're gonna add medicines from seed data or django admin so a list and retrieve APIs would be enough

2023-05-04 04:07 UTC, Kavindu-248 commented on apps/dispensary/views.py
> +class MedicineViewSet(viewsets.ModelViewSet):
Changed to a ViewSet with the list and retrieve methods.

2023-05-08 03:01 UTC, Raam124 requested changes

2023-05-08 03:01 UTC, Raam124 commented on apps/dispensary/views.py
> +        queryset = Medicine.objects.all()
here directly query the single medicine no need to get all and again get one from that query make a single query

2023-05-08 03:31 UTC, Kavindu-248 commented on apps/dispensary/views.py
> +        queryset = Medicine.objects.all()
removed querying of all medicine objects

2023-05-08 03:35 UTC, Raam124 approved these changes

2023-05-08 03:35 UTC, merged