Fix : changed the relationship between Pharmacy and  the Pharmacy_user
Kavindu-248/DRF_Build pull request #21
Opened 2023-05-08 06:54 UTC by Kavindu-248

2023-05-08 07:54 UTC, Raam124 requested changes

2023-05-08 07:54 UTC, Raam124 commented on apps/dispensary/views.py
> +class PharmacyViewSet(viewsets.ModelViewSet):
we can't have a create method for pharmacy add a function to create a pharmacy automatically when a pharmacy user is registering

2023-05-08 07:55 UTC, Raam124 requested changes

2023-05-08 07:55 UTC, Raam124 commented on apps/dispensary/views.py
> +class PharmacyViewSet(viewsets.ModelViewSet):
only need tt have a get and update endpoints here

2023-05-09 20:15 UTC, Kavindu-248 commented on apps/dispensary/views.py
> +class PharmacyViewSet(viewsets.ModelViewSet):
Updated the necessary changes

2023-05-10 04:44 UTC, Raam124 requested changes

2023-05-10 04:44 UTC, Raam124 commented on apps/dispensary/views.py
> +class PharmacyViewSet(viewsets.ModelViewSet):
the modelviewset will automatically enable all the method better use the viewset here

2023-05-10 04:44 UTC, Raam124 commented on apps/dispensary/views.py
> +
do not leave white space like this

2023-05-10 04:44 UTC, Raam124 commented on apps/users/serializers.py
> +                  'email', 'password', 'confirm_password', 'phone', 'role', 'pharmacy_name', 'address']
do not get address here just keep it null user can update it later

2023-05-10 05:52 UTC, Kavindu-248 commented on apps/dispensary/views.py
> +class PharmacyViewSet(viewsets.ModelViewSet):
Changed to ViewSet custom list and update methods

2023-05-10 05:52 UTC, Kavindu-248 commented on apps/dispensary/views.py
> +
noted.

2023-05-10 05:52 UTC, Kavindu-248 commented on apps/users/serializers.py
> +                  'email', 'password', 'confirm_password', 'phone', 'role', 'pharmacy_name', 'address']
Removed address from the fields, up-to user to update the data.

2023-05-10 15:22 UTC, Raam124 requested changes

2023-05-10 15:22 UTC, Raam124 commented on apps/dispensary/views.py
> +        data={
directly access the data do not have to declare a dict again here

2023-05-11 02:48 UTC, Kavindu-248 commented on apps/dispensary/views.py
> +        data={
removed the dictionary

2023-05-11 09:27 UTC, Raam124 approved these changes

2023-05-11 09:27 UTC, merged