feat: minor tweaks to adjust the creation of a prescription object in…
Kavindu-248/DRF_Build pull request #28
Opened 2023-05-22 20:22 UTC by Kavindu-248

… assesment app

2023-05-23 03:17 UTC, Raam124 requested changes

2023-05-23 03:17 UTC, Raam124 commented on apps/assesment/views.py
> +            prescription = Prescription.objects.create(appointment=appointment)
what if the prescription is not available?

2023-05-23 03:17 UTC, Raam124 commented on apps/assesment/views.py
> +                    Prescription.objects.create(form_assesment=form_assesment)
what if the prescription is not available?

2023-05-23 03:17 UTC, Raam124 commented on apps/dispensary/views.py
> +class PrescriptionViewSet(viewsets.ModelViewSet):
model view set allows all methods inbuilt we don't need those here

2023-05-23 04:30 UTC, Kavindu-248 commented on apps/assesment/views.py
> +            prescription = Prescription.objects.create(appointment=appointment)
added a validation error.

2023-05-23 04:30 UTC, Kavindu-248 commented on apps/assesment/views.py
> +                    Prescription.objects.create(form_assesment=form_assesment)
added a validation error.

2023-05-23 04:31 UTC, Kavindu-248 commented on apps/dispensary/views.py
> +class PrescriptionViewSet(viewsets.ModelViewSet):
changed to viewset with list and update methods

2023-05-23 06:26 UTC, Raam124 requested changes

2023-05-23 06:26 UTC, Raam124 commented on apps/assesment/views.py
> +            else:
reread the scenario prescription is optional. these are requirements

2023-05-23 07:18 UTC, Kavindu-248 commented on apps/assesment/views.py
> +            else:
ammended the code to match if a prescripotion is needed in the payload prescription gets passed as 'true'

2023-05-23 08:20 UTC, Raam124 requested changes

2023-05-23 08:20 UTC, Raam124 commented on apps/assesment/views.py
> +        prescription_needed = self.request.data.get('prescription', False)
this is not the way to check if a key is there

2023-05-23 09:33 UTC, Raam124 requested changes

2023-05-23 09:33 UTC, Raam124 commented on apps/assesment/views.py
> +                serializer.save(prescription=None)
why are you passing none here prescription is not a mandatory field right?

2023-05-23 09:42 UTC, Kavindu-248 commented on apps/assesment/views.py
> +                serializer.save(prescription=None)
Yea prescription is optional ,checked by default it will be null, should have not explicitly set it.

2023-05-24 04:25 UTC, Raam124 approved these changes

2023-05-24 04:26 UTC, merged