feat: Models added for the specific apps
Kavindu-248/DRF_Build pull request #3
Opened 2023-02-07 09:23 UTC by Kavindu-248

2023-02-07 09:35 UTC, Raam124 requested changes

2023-02-07 09:35 UTC, Raam124 commented on apps/users/models.py
> +        User, on_delete=models.CASCADE, null=False)
one to-one field has defaulted to null False you don't have to specify it. check all other places

2023-02-07 09:35 UTC, Raam124 commented on apps/dispensary/models.py
> +        Pharmacy, null=False, verbose_name='Pharmacies')
Don't use verbose names use related names instead. check the related name Django documentation first. check all other fields

2023-02-07 10:32 UTC, Kavindu-248 reviewed
Removed Null values from one to one fields
changed verbose name to related_name in relation with django docs

2023-02-09 05:05 UTC, Raam124 requested changes

2023-02-09 08:48 UTC, Raam124 requested changes

2023-02-09 08:48 UTC, Raam124 commented on apps/assesment/models.py
> +    treatment_options = models.CharField(
a field cannot be in the plural it only gonna hold a single item for a record. Also, the system can't decide on a default value for treatment options it's not specified anywhere

2023-02-09 08:48 UTC, Raam124 commented on apps/assesment/models.py
> +    answered = models.BooleanField(default=False)
What's the purpose of `answered` field?

2023-02-09 08:48 UTC, Raam124 commented on apps/dispensary/models.py
> +class Prescription(models.Model):
prescriptions should have the quantity of the medication

2023-02-10 05:15 UTC, Raam124 requested changes

2023-02-10 05:15 UTC, Raam124 commented on apps/dispensary/models.py
> +class ServiceProvided(models.TextChoices):
rename the class to indicate this a set of types

2023-02-10 05:15 UTC, Raam124 commented on apps/dispensary/models.py
> +    quantity = models.CharField(max_length=100)
quantity can't be a char

2023-02-10 05:15 UTC, Raam124 commented on apps/dispensary/models.py
> +class Order(models.Model):
where are the other relationships with Order ?

2023-02-10 09:03 UTC, Raam124 requested changes

2023-02-10 09:03 UTC, Raam124 commented on apps/dispensary/models.py
> +class Prescription(models.Model):
a precription canont belong to both services

2023-02-10 09:03 UTC, Raam124 commented on apps/dispensary/models.py
> +class Medicine(models.Model):
precriotion medicine relation is missing it's also incorrect in ERD check that

2023-02-10 09:03 UTC, Raam124 commented on apps/dispensary/models.py
> +class Invoice(models.Model):
Order relation is missed out

2023-02-10 09:03 UTC, Raam124 commented on apps/dispensary/models.py
> +    invoice = models.OneToOneField(
incorrect relation

2023-02-10 09:03 UTC, Raam124 commented on apps/dispensary/models.py
> +        FormAssessment, on_delete=models.CASCADE, related_name='orders', null=True)
if uyou use null True use blank True as well

2023-02-10 09:03 UTC, Raam124 commented on apps/dispensary/models.py
> +        Pharmacy,  related_name='Pharmacies')
related names should be all simple letters

2023-02-10 09:03 UTC, Raam124 commented on apps/dispensary/models.py
> +    vaccine = models.ManyToManyField(
M2M fields are defaulty null. refer the doc

2023-02-13 05:43 UTC, Raam124 requested changes

2023-02-13 05:43 UTC, Raam124 commented on apps/assesment/models.py
> +   duration = models.DurationField(default=timedelta(minutes=15))
check the limitations of duration field in the doc

2023-02-13 05:43 UTC, Raam124 commented on apps/assesment/models.py
> +    order = models.OneToOneField(
this order relationship is incorrect

2023-02-14 04:02 UTC, Kavindu-248 commented on apps/assesment/models.py
> +class Avalability(models.Model):
In the Availability model Should I add a list of choices containing ,Time slots.

2023-02-14 10:15 UTC, Kavindu-248 commented on apps/users/models.py
> +        User, on_delete=models.CASCADE, null=False)
Went through the documentation to clarify regarding the null values , and amended the changes in the rest of the code

2023-02-14 10:16 UTC, Kavindu-248 commented on apps/assesment/models.py
> +    DIABETES = 'DIABETES', 'Diabetes'
Name choice changed to TreatmentOption.

2023-02-14 10:18 UTC, Kavindu-248 commented on apps/assesment/models.py
> +    sickness = models.CharField(
Field name changed to treatment_option inline to match with the choice list.

2023-02-14 10:21 UTC, Kavindu-248 commented on apps/assesment/models.py
> +class Avalability(models.Model):
Went through the scenario to understand doctors marking appointment slots of 15minutes hence added a duration field with an IntervalField

2023-02-14 10:50 UTC, Kavindu-248 commented on apps/assesment/models.py
> +    answered = models.BooleanField(default=False)
Answered field removed - unessecary field

2023-02-14 10:51 UTC, Kavindu-248 commented on apps/assesment/models.py
> +    treatment_options = models.CharField(
Cross-referenced the documentation in model field reference, changed the field names to singular

2023-02-14 11:07 UTC, Kavindu-248 commented on apps/dispensary/models.py
> +    quantity = models.CharField(max_length=100)
chanaged to an IntegerField

2023-02-14 11:12 UTC, Kavindu-248 commented on apps/dispensary/models.py
> +        Pharmacy,  related_name='Pharmacies')
across the code base amended this mistake.

2023-02-14 11:12 UTC, Kavindu-248 commented on apps/dispensary/models.py
> +        FormAssessment, on_delete=models.CASCADE, related_name='orders', null=True)
Referred the documentation and rectified this error

2023-02-14 11:19 UTC, Kavindu-248 commented on apps/assesment/models.py
> +    doctor = models.ForeignKey(
Rectified with double checking the ERD as its an mandatory relationship an appointment should have a doctor null = false

2023-02-14 11:24 UTC, Kavindu-248 commented on apps/assesment/models.py
> +   duration = models.DurationField(default=timedelta(minutes=15))
Since PostgresSQL is being used as our database, the data type that should be used is Interval hence DurationField is removed.

2023-02-14 11:26 UTC, Kavindu-248 commented on apps/dispensary/models.py
> +    assessment = models.OneToOneField(
across the codebase, changed the relevant field names to the model name

2023-02-14 11:32 UTC, Kavindu-248 commented on apps/dispensary/models.py
> +class Prescription(models.Model):
in relation with the ERD, prescription relationship changed

2023-02-15 03:51 UTC, Kavindu-248 commented on apps/assesment/models.py
> +    time = models.DateTimeField()
Referred the scenario and understood my mistake here and removed the fields.

2023-02-15 03:58 UTC, Kavindu-248 commented on apps/assesment/models.py
> +    attachment = models.ForeignKey(
Attachment relationship removed, as it doesnt belong under appointment model.

2023-02-15 04:05 UTC, Kavindu-248 commented on apps/assesment/models.py
> +class Attachment(models.Model):
Inserted the appointment field, referenced the ERD to map out the relationship.

2023-02-15 04:28 UTC, Kavindu-248 commented on apps/assesment/models.py
> +
Had a confusion before, cross checked the scenario and added the related field.

2023-02-15 04:39 UTC, Raam124 requested changes

2023-02-15 04:39 UTC, Raam124 commented on apps/assesment/models.py
> +class Avalability(models.Model):
no need for a duration field manage it with start time and end time with the date field too

2023-02-15 04:39 UTC, Raam124 commented on apps/assesment/models.py
> +        Appointment, on_delete=models.CASCADE, related_name='attachments', null=True, blank=True)
why the appointment FK is null here?

2023-02-15 04:39 UTC, Raam124 commented on apps/dispensary/models.py
> +class Prescription(models.Model):
add the one to one field in prescription table

2023-02-15 04:48 UTC, Kavindu-248 commented on apps/assesment/models.py
> +        Appointment, on_delete=models.CASCADE, related_name='attachments', null=True, blank=True)
I had a confusion and the more I wrote the models code I realised I needed to read the relationships in reverse.

2023-02-16 09:34 UTC, Raam124 requested changes

2023-02-16 09:34 UTC, Raam124 commented on apps/dispensary/models.py
> +    form_assesment = models.OneToOneField('assesment.FormAssesment', on_delete=models.CASCADE, related_name='prescriptions')
one to one field related name should be in singular

2023-02-16 09:34 UTC, Raam124 commented on apps/dispensary/models.py
> +    appointment = models.OneToOneField('assesment.Appointment', on_delete=models.CASCADE, related_name='prescriptions')
one to one field related name should be in singular

2023-02-16 09:34 UTC, Raam124 commented on apps/dispensary/models.py
> +    form_assesment = models.OneToOneField('assesment.FormAssesment', on_delete=models.CASCADE, related_name='orders')
one to one field related name should be in singular

2023-02-16 09:34 UTC, Raam124 commented on apps/dispensary/models.py
> +    prescription = models.OneToOneField(Prescription, on_delete=models.CASCADE, related_name='orders')
one to one field related name should be in singular

2023-02-17 03:59 UTC, Raam124 requested changes

2023-02-17 03:59 UTC, Raam124 commented on apps/dispensary/models.py
> +class Order(models.Model):
Where is Appointment and Order relationship ?

2023-02-17 03:59 UTC, Raam124 commented on apps/assesment/models.py
> +    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='appointments')
why order is in the APpointment model and why it's a FK?

2023-02-17 03:59 UTC, Raam124 commented on apps/assesment/models.py
> +    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='form_assesments')
why form assessment order one to one relationship is mapped is in both table Form assessment here and in Order table as well ?

2023-02-17 04:07 UTC, Kavindu-248 commented on apps/dispensary/models.py
> +class Order(models.Model):
I have mixed up the two I changed it

2023-02-17 06:58 UTC, Raam124 approved these changes

2023-02-17 07:09 UTC, merged