feat: assignment of a prescription to a pharmacy
Kavindu-248/DRF_Build pull request #31
Opened 2023-05-24 08:02 UTC by Kavindu-248

2023-05-24 12:47 UTC, Raam124 requested changes

2023-05-24 13:01 UTC, Kavindu-248 commented on apps/dispensary/views.py
> +        if 'pharmacy' in request.data:
@Raam124  over there  that feature is associating a prescription to a pharmacy is the feature , or have I misinterpreted.

2023-05-24 13:02 UTC, Raam124 commented on apps/dispensary/views.py
> +        if 'pharmacy' in request.data:
Recheck with the scenario

2023-05-25 09:09 UTC, Kavindu-248 commented on apps/assesment/serializers.py
@Raam124  I thought the missing link was when creating an appointment or assesment the user can select the pharmacy , _" These prescriptions are sent to a pharmacy preselected by the patient at the creation of the video or form assessment order."_

2023-05-25 10:33 UTC, Raam124 approved these changes

2023-05-25 10:33 UTC, Raam124 commented on apps/assesment/serializers.py
understood

2023-05-25 10:34 UTC, merged