feat: added the order- API
Kavindu-248/DRF_Build pull request #37
Opened 2023-05-26 07:30 UTC by Kavindu-248

2023-05-29 03:36 UTC, Raam124 requested changes

2023-05-29 03:36 UTC, Raam124 commented on apps/assesment/views.py
> +                order = Order.objects.create(appointment=appointment)
did you test this manually isn't this throwing an error ?what is the logic behind this ?

2023-05-29 03:36 UTC, Raam124 commented on apps/assesment/views.py
> +                        order = Order.objects.create(form_assesment=form_assesment)
same above issue

2023-05-29 04:38 UTC, Kavindu-248 commented on apps/assesment/views.py
> +                        order = Order.objects.create(form_assesment=form_assesment)
view above comment

2023-05-29 04:39 UTC, Kavindu-248 commented on apps/assesment/views.py
> +                order = Order.objects.create(appointment=appointment)
@Raam124 , I went with the approach, when the appointment/form-assessment is Created the initial status of it is _PENDING_, later  we can update the status to completed/cancelled, when its set to _COMPLETED_ the order gets created to that relevant id of the appointment/form-assessment, In POSTMAN I used a GET method to check if the specific order object is created. If there is an error to this logic, I can recheck and change the code.

2023-05-30 04:48 UTC, Raam124 requested changes

2023-05-30 04:48 UTC, Raam124 commented on apps/assesment/views.py
> +            order = Order.objects.create(appointment=appointment)
this is the appointment update function right how did you only check this with a GET method? just update this method POSTMAN screenshot with the response here

2023-05-30 05:06 UTC, Kavindu-248 commented on apps/assesment/views.py
> +            order = Order.objects.create(appointment=appointment)
![UPDATE](https://github.com/Kavindu-248/DRF_Build/assets/62738886/d264bd49-537a-479a-b26c-fbc39499c245)
This is the appointment update, status set to COMPLETE,
And this is the corresponding order created.
![GET](https://github.com/Kavindu-248/DRF_Build/assets/62738886/500fd615-4fed-4ad1-9ca6-bcf37078fddc)
@Raam124

2023-05-30 05:13 UTC, Raam124 requested changes

2023-05-30 05:13 UTC, Raam124 commented on apps/assesment/views.py
> +            order = Order.objects.create(appointment=appointment)
@Kavindu-248 what's the use of this line in appointment and form assessment  serializer `serializer.save(order=order)`

2023-05-30 05:51 UTC, Kavindu-248 commented on apps/assesment/views.py
> +            order = Order.objects.create(appointment=appointment)
Removed, in the new commit an order field is not needed.

2023-05-30 06:45 UTC, Raam124 requested changes

2023-05-30 06:45 UTC, Raam124 commented on apps/assesment/views.py
you need to create an order when a prescription is created too check that logic

2023-06-01 05:36 UTC, Kavindu-248 commented on apps/assesment/views.py
prescription assigned to relevant order when a Prescription is created.

2023-06-06 05:44 UTC, Raam124 requested changes

2023-06-06 05:44 UTC, Raam124 commented on apps/dispensary/views.py
> +        order_appointment = Order.objects.filter(appointment=prescription.appointment)
you have the prescription object here access the related appointment/assessment object directly instead of these two queries

2023-06-06 05:44 UTC, Raam124 commented on apps/dispensary/views.py
> +        if prescription.prescription_status == PrescriptionStatus.ACCEPTED:
prescription initial status would be pending so if it's not in a pending state directly raise an error saying use can't edit it. unless it is in the status payload gonna have a status either accept or reject based on that you have make the logic here

2023-06-06 06:24 UTC, Kavindu-248 commented on apps/dispensary/views.py
> +        order_appointment = Order.objects.filter(appointment=prescription.appointment)
Removed, the extra two queries

2023-06-11 20:23 UTC, closed without merging