fix: altered the prescription and medicine models as M2M relationship
Kavindu-248/DRF_Build pull request #38
Opened 2023-06-06 11:27 UTC by Kavindu-248

2023-06-07 03:36 UTC, Raam124 requested changes

2023-06-07 03:36 UTC, Raam124 commented on apps/dispensary/models.py
> +class PrescriptionMedicine(models.Model):
check both FKs related names those are incorrect

2023-06-07 04:42 UTC, Kavindu-248 commented on apps/dispensary/models.py
> +class PrescriptionMedicine(models.Model):
Changed the relevant name

2023-06-07 05:06 UTC, Raam124 requested changes

2023-06-07 05:06 UTC, Raam124 commented on apps/dispensary/models.py
> +class PrescriptionMedicine(models.Model):
these are still not relevant names just make sure you got how related names work

2023-06-07 17:47 UTC, Raam124 requested changes

2023-06-07 17:47 UTC, Raam124 commented on apps/dispensary/models.py
> +class PrescriptionMedicine(models.Model):
this is still irrelevant

2023-06-08 10:57 UTC, Raam124 requested changes

2023-06-09 04:14 UTC, Raam124 approved these changes

2023-06-09 04:14 UTC, merged