feat: reinstated the pharmacy API
Kavindu-248/DRF_Build pull request #42
Opened 2023-06-12 08:56 UTC by Kavindu-248

2023-06-12 09:13 UTC, Raam124 requested changes

2023-06-12 09:26 UTC, Kavindu-248 commented on apps/dispensary/views.py
Added.

2023-06-12 10:21 UTC, Raam124 requested changes

2023-06-12 10:21 UTC, Raam124 commented on apps/dispensary/views.py
> +    def update(self, request):
this is update request how did work without even passing a id in url ?

2023-06-12 10:34 UTC, Kavindu-248 commented on apps/dispensary/views.py
> +    def update(self, request):
@Raam124  added the pk parameter, apologies a careless mistake from my side

2023-06-13 03:46 UTC, Raam124 approved these changes

2023-06-13 03:46 UTC, merged