feat: form-assement queryset filtration
Kavindu-248/DRF_Build pull request #50
Opened 2023-06-15 06:06 UTC by Kavindu-248

2023-06-15 10:28 UTC, Raam124 requested changes

2023-06-15 10:28 UTC, Raam124 commented on apps/assesment/views.py
> +        if self.request.user.role == Roles.DOCTOR:
doctor will be able to see all the footprint to pick one to himself initially that feature is missing here

2023-06-16 03:20 UTC, Kavindu-248 commented on apps/assesment/views.py
> +        if self.request.user.role == Roles.DOCTOR:
Change made

2023-06-16 04:38 UTC, Raam124 requested changes

2023-06-16 04:38 UTC, Raam124 commented on apps/assesment/views.py
> +            return FormAssesment.objects.filter(Q(doctor=self.request.user.doctor) | Q(doctor__isnull=True))
did you manually check is this `doctor__isnull=True` condition working? if yes attach a screenshot here of the result

2023-06-16 04:59 UTC, Kavindu-248 commented on apps/assesment/views.py
> +            return FormAssesment.objects.filter(Q(doctor=self.request.user.doctor) | Q(doctor__isnull=True))
@Raam124 
![image](https://github.com/Kavindu-248/DRF_Build/assets/62738886/2df3abd1-21a3-407e-8553-daea632ebb79)

2023-06-20 03:51 UTC, Raam124 approved these changes

2023-06-20 03:51 UTC, merged