feat: queryset filteration for prescriptionAPI
Kavindu-248/DRF_Build pull request #51
Opened 2023-06-15 08:16 UTC by Kavindu-248

2023-06-15 10:29 UTC, Raam124 requested changes

2023-06-15 10:29 UTC, Raam124 commented on apps/dispensary/views.py
> +    def get_queryset(self):
pharmacy user needs to see the prescriptions too

2023-06-16 03:20 UTC, Kavindu-248 commented on apps/dispensary/views.py
> +    def get_queryset(self):
added acess to pharmacy user

2023-06-16 04:35 UTC, Raam124 requested changes

2023-06-16 04:35 UTC, Raam124 commented on apps/dispensary/views.py
> +            return Prescription.objects.filter(medicines__pharmacy__pharmacy_user = self.request.user.pharmacyuser)
same issue here is there a pharmacy field in prescription?

2023-06-19 10:48 UTC, merged