feat: query-set filtration for Order Api
Kavindu-248/DRF_Build pull request #52
Opened 2023-06-15 10:06 UTC by Kavindu-248

2023-06-15 10:29 UTC, Raam124 commented on apps/dispensary/views.py
>      def list(self, request):
pharmacy user has access to order

2023-06-16 03:20 UTC, Kavindu-248 commented on apps/dispensary/views.py
>      def list(self, request):
added acces to pharamacy user

2023-06-16 04:33 UTC, Raam124 requested changes

2023-06-16 04:33 UTC, Raam124 commented on apps/dispensary/views.py
> +            queryset = queryset.filter(prescription__medicines__pharmacy__pharmacy_user=self.request.user.pharmacyuser)
why are you filtering like this pharmacy should be in order table if not add that field and change the logics according to that in other places

2023-06-19 10:39 UTC, merged