feat: QuerySet filtration for the pharmacy API
Kavindu-248/DRF_Build pull request #56
Opened 2023-06-20 05:02 UTC by Kavindu-248

2023-06-20 06:26 UTC, Raam124 requested changes

2023-06-20 06:26 UTC, Raam124 commented on apps/dispensary/views.py
> +            queryset = queryset.filter(pharmacy_user=self.request.user.pharmacyuser)
this is a one-to-one relation right? use the related object to get

2023-06-20 09:38 UTC, Kavindu-248 commented on apps/dispensary/views.py
> +            queryset = queryset.filter(pharmacy_user=self.request.user.pharmacyuser)
change made

2023-06-21 04:09 UTC, Raam124 approved these changes

2023-06-21 04:09 UTC, merged