fix: removed pharmacy field from medicine model
Kavindu-248/DRF_Build pull request #58
Opened 2023-06-20 10:41 UTC by Kavindu-248

2023-06-21 04:08 UTC, Raam124 requested changes

2023-06-21 04:08 UTC, Raam124 commented on apps/dispensary/migrations/0021_remove_medicine_pharmacy.py
did you read the scenario this why did you remove this relation ?

2023-06-21 06:16 UTC, Kavindu-248 commented on apps/dispensary/migrations/0021_remove_medicine_pharmacy.py
@Raam124 rechecked the scenario, re-added the field , it was a confusion

2023-06-22 04:42 UTC, Raam124 approved these changes

2023-06-22 04:42 UTC, merged