feat: permission class for the access of assessment
Kavindu-248/DRF_Build pull request #60
Opened 2023-06-26 06:24 UTC by Kavindu-248

2023-06-26 10:08 UTC, Raam124 requested changes

2023-06-26 10:08 UTC, Raam124 commented on apps/users/permissions.py
> +class IsAllowedToAccessFormAssesment(BasePermission):
permission must be named based on user permission levels not for a specific resource

2023-06-26 10:23 UTC, Kavindu-248 commented on apps/users/permissions.py
> +class IsAllowedToAccessFormAssesment(BasePermission):
Name changed

2023-06-27 04:47 UTC, Raam124 requested changes

2023-06-27 04:47 UTC, Raam124 commented on apps/users/permissions.py
> +            if obj.doctor is not None and obj.doctor != request.user:
if the doctor is none you should return those form assessments right? check this whole condition again

2023-06-27 07:16 UTC, Kavindu-248 commented on apps/users/permissions.py
> +            if obj.doctor is not None and obj.doctor != request.user:
added a condition to check when doctor is none.

2023-06-27 10:18 UTC, Raam124 requested changes

2023-06-27 10:18 UTC, Raam124 commented on apps/users/permissions.py
> +            elif obj.doctor is None:
why do you need the elif block does the if block satisfy this condition as well right?

2023-06-27 11:09 UTC, Kavindu-248 commented on apps/users/permissions.py
> +            elif obj.doctor is None:
Noted, removed not none conditon to return. assements where doctor is null.

2023-06-28 04:42 UTC, Raam124 approved these changes

2023-06-28 04:42 UTC, merged