feat: introduced endpoint and function to dispatch an order
Kavindu-248/DRF_Build pull request #66
Opened 2023-07-11 02:55 UTC by Kavindu-248

2023-07-11 04:05 UTC, Raam124 requested changes

2023-07-11 04:05 UTC, Raam124 commented on apps/dispensary/views.py
> +    @action(detail=True, methods=['post'], url_path='dispatch-order', permission_classes=[IsPharmacyUser] )
`dispatch-order` url path cannot contain actions like names like this Also you're updating an order why do we need a separate API for this?

2023-07-11 05:50 UTC, Kavindu-248 commented on apps/dispensary/views.py
> +    @action(detail=True, methods=['post'], url_path='dispatch-order', permission_classes=[IsPharmacyUser] )
removed the custom API made changes in the update method.

2023-07-12 07:02 UTC, Raam124 approved these changes

2023-07-12 07:02 UTC, merged