feat: introduced endpoint to get vaccines for the patient
Kavindu-248/DRF_Build pull request #67
Opened 2023-07-12 09:08 UTC by Kavindu-248

2023-07-18 04:17 UTC, Raam124 requested changes

2023-07-18 04:17 UTC, Raam124 commented on apps/dispensary/views.py
> +        queryset = Medicine.objects.filter(description="Vaccine")
u cant add filters by a string value maintain a medicine type in this case

2023-07-18 05:15 UTC, Kavindu-248 commented on apps/dispensary/views.py
> +        queryset = Medicine.objects.filter(description="Vaccine")
added choice field in the models filtered to medicine type

2023-07-19 04:09 UTC, Raam124 approved these changes

2023-07-19 04:10 UTC, Raam124 requested changes

2023-07-19 04:10 UTC, Raam124 commented on apps/dispensary/views.py
> +        queryset = Medicine.objects.filter(medicine_type='VACCINE')
filter by type instead of string here

2023-07-19 04:49 UTC, Kavindu-248 commented on apps/dispensary/views.py
> +        queryset = Medicine.objects.filter(medicine_type='VACCINE')
Apologies, added filtration for type

2023-07-20 07:29 UTC, Raam124 approved these changes

2023-07-20 07:29 UTC, merged