feat: added endpoint to get availability for a specific doctor.
Kavindu-248/DRF_Build pull request #68
Opened 2023-07-17 10:03 UTC by Kavindu-248

2023-07-18 04:19 UTC, Raam124 requested changes

2023-07-18 04:19 UTC, Raam124 commented on apps/assesment/views.py
> +    @action(detail=False, methods=['get'], url_path='(?P<doctor_id>[^/.]+)/availabilities')
first, get the doctor and check if the doctor exists or throw 404. Then get the availabilities using the related name

2023-07-18 05:15 UTC, Kavindu-248 commented on apps/assesment/views.py
> +    @action(detail=False, methods=['get'], url_path='(?P<doctor_id>[^/.]+)/availabilities')
Change made

2023-07-19 04:09 UTC, Raam124 requested changes

2023-07-19 04:09 UTC, Raam124 commented on apps/assesment/views.py
> +        queryset = Avalability.objects.filter(doctor=doctor, booked=False)
use related names here

2023-07-19 04:48 UTC, Kavindu-248 commented on apps/assesment/views.py
> +        queryset = Avalability.objects.filter(doctor=doctor, booked=False)
Change added

2023-07-20 07:29 UTC, Raam124 requested changes

2023-07-20 07:29 UTC, Raam124 commented on apps/assesment/views.py
> +        queryset = Avalability.objects.filter(doctor__id=doctor_id, booked=False )
not like this use the related name to fetch the related objects refer the docs

2023-07-20 10:32 UTC, Kavindu-248 commented on apps/assesment/views.py
> +        queryset = Avalability.objects.filter(doctor__id=doctor_id, booked=False )
Amended the code

2023-07-24 04:25 UTC, Raam124 approved these changes

2023-07-24 04:25 UTC, merged