feat : added  CRUD functionality to the availability model
Kavindu-248/DRF_Build pull request #7
Opened 2023-02-23 04:44 UTC by Kavindu-248

2023-02-23 05:52 UTC, Raam124 requested changes

2023-02-23 05:52 UTC, Raam124 commented on project/urls.py
> +    path('api/', include('apps.assesment.urls')),
This is not the right way to add a url for a modelviewset

2023-02-23 05:52 UTC, Raam124 commented on apps/assesment/views.py
> +    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
this API is not available for non authenticated users even the GET

2023-02-23 05:52 UTC, Raam124 commented on project/urls.py
> +    path('api/', include('apps.assesment.urls')),
check the existing one in users app or check the docs

2023-02-23 07:16 UTC, Kavindu-248 commented on apps/assesment/views.py
> +    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
checked docs and changed to IsAuthenticated

2023-02-23 07:16 UTC, Kavindu-248 commented on project/urls.py
> +    path('api/', include('apps.assesment.urls')),
Checked the users app to gain an idea and made the required change

2023-02-23 07:27 UTC, Raam124 requested changes

2023-02-23 07:27 UTC, Raam124 commented on project/urls.py
> +router.register('avalability', AvalabilityViewSet, basename='avalability')
follow the REST API best practices. it should be `availabilities`

2023-02-23 07:57 UTC, Kavindu-248 commented on project/urls.py
> +router.register('avalability', AvalabilityViewSet, basename='avalability')
Referred articles on REST API design best practice and rectified the change

2023-02-23 08:58 UTC, Raam124 requested changes

2023-02-23 08:58 UTC, Raam124 commented on apps/assesment/views.py
> +class AvalabilityViewSet(viewsets.ModelViewSet):
This will throw a null value error in the doctor id in POST

2023-02-28 03:55 UTC, Kavindu-248 commented on apps/assesment/views.py
> +class AvalabilityViewSet(viewsets.ModelViewSet):
Referred the documentation to make the nescessary changes

2023-02-28 04:18 UTC, Raam124 requested changes

2023-02-28 04:18 UTC, Raam124 commented on apps/assesment/views.py
> +class AvalabilityViewSet(viewsets.ModelViewSet):
@Kavindu-248 this is not the way to do to also you can't set an default doctor

2023-03-21 08:53 UTC, closed without merging