feat: view.py amended to register user roles
Kavindu-248/DRF_Build pull request #9
Opened 2023-03-01 09:29 UTC by Kavindu-248

2023-03-08 03:47 UTC, Raam124 requested changes

2023-03-08 03:47 UTC, Raam124 commented on apps/users/views.py
> +            role = request.data.get('role')
This part is triggered after the user instance is saved so it might get saved with a default role. There's no point in checking the role afterward. just find a suitable approach

2023-03-14 11:17 UTC, Kavindu-248 commented on apps/users/views.py
> +            role = request.data.get('role')
Referred the documentation and had to refreshen my python knowledge to make sure I understood where I had to change

2023-03-14 14:58 UTC, Raam124 requested changes

2023-03-15 05:56 UTC, Kavindu-248 commented on apps/users/views.py
> +            if role == 'DOCTOR':
Code Amended to match the requirements

2023-03-15 07:25 UTC, Raam124 requested changes

2023-03-15 07:25 UTC, Raam124 commented on apps/users/views.py
> +            user = serializer.save()
why this change is needed? Is the existing code not working as expected?

2023-03-15 07:25 UTC, Raam124 commented on apps/users/serializers.py
> +                Doctor.objects.create(User=user)
why use the user model instead of the user field when assigning?

2023-03-17 03:12 UTC, Kavindu-248 commented on apps/users/views.py
> +            user = serializer.save()
Given code worked mistakenly removed serializer.data from Response

2023-03-17 05:24 UTC, Kavindu-248 commented on apps/users/serializers.py
> +                Doctor.objects.create(User=user)
Amended to take in user field

2023-03-17 05:38 UTC, Raam124 requested changes

2023-03-17 05:38 UTC, Raam124 commented on apps/users/views.py
> +            return Response(serializer.data, status=status.HTTP_201_CREATED)
why is this change needed?

2023-03-20 03:58 UTC, Raam124 requested changes

2023-03-20 03:58 UTC, Raam124 commented on apps/users/views.py
> +            serializer = ProfileUpdateSerializer(
remove these unwanted space changes

2023-03-20 03:58 UTC, Raam124 commented on apps/users/views.py
> +        serializer = PasswordChangeSerializer(
remove these unwanted space changes

2023-03-20 03:58 UTC, Raam124 commented on apps/users/views.py
> +
remove these unwanted space changes

2023-03-20 03:58 UTC, Raam124 commented on apps/users/serializers.py
> +        required=True, write_only=True, min_length=6,)
remove these unwanted "," at the end

2023-03-20 05:40 UTC, Kavindu-248 commented on apps/users/views.py
> +            serializer = ProfileUpdateSerializer(
Had disable format on save option on my VSCode hence why this unwanted space arose

2023-03-20 05:41 UTC, Kavindu-248 commented on apps/users/views.py
> +        serializer = PasswordChangeSerializer(
Had disable format on save option on my VSCode hence why this unwanted space arose

2023-03-20 05:41 UTC, Kavindu-248 commented on apps/users/views.py
> +
Had disable format on save option on my VSCode hence why this unwanted space arose

2023-03-20 09:54 UTC, Raam124 approved these changes

2023-03-20 09:54 UTC, merged